<?php

class Design_model extends CI_Model {
	  public function __construct() {
        parent::__construct();
        	$this->load->database();

    }
/**
 * [get_design_mr_no description]
 * @return [type] [Here Mr No For The creation of material autogenerated  with new mar no]
 */
    public function get_design_mr_no(){
      while (1) {
        $mr_no_no=date('Y-m-d').'-'.random_string('alnum',5);
        $data_array_mr = array('mr_no' => $mr_no_no );
        $query_mr=$this->db->get_where('master_mr_job_details',$data_array_mr);
        if ($query_mr->num_rows() == 0) {
          return $mr_no_no;
          exit;
        }
      }
    }
  /**
   * [get_design_mr_no_deatils description]
   * @param  [type] $value [Here Mr No or serail number is been  user get information for sci moi or logistics]
   * @return [type]        [no_mr=>2 ] if serail no dont matched with id inside tavle will make redirect to logout
   *                       [no_mr=>1 ]  if it 1 then information will be send back to it is scuucess and get parameter will is incude to populated the tables      
   */
    public function get_design_mr_no_deatils($value){
        $data_array_mr = array('slno_mr' => $value);
        $query_mr=$this->db->get_where('master_mr_job_details',$data_array_mr);
        if($query_mr->num_rows() == 0){
        $data_send = array('no_mr' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_mr->result();
        $data_send = array('no_mr' =>1, 'mr_details'=>$results);
        return $data_send;
        exit;
      } 
    }
    /**
     * [get_design_mr_no_check description]
     * @param  [type] $data_id [before inserting in data base this function is been use to check wheather information is stored or not
     * @return [type]          [if 1=> hen success or else no mr no is present inside data base]
     */
    public function get_design_mr_no_check($data_id){
        $data_array_mr = array('mr_no' => $data_id );
        $query_mr=$this->db->get_where('master_mr_job_details',$data_array_mr);
        if ($query_mr->num_rows() == 0) {
          return 1;
          exit;
        }else{
          return 3;
          exit;
        }
     
    }
    public function get_design_mr_no_check_m($data_id){
        $data_array_mr = array('pr_no' => $data_id );
        $query_mr=$this->db->get_where('master_mr_job_details_m',$data_array_mr);
        if ($query_mr->num_rows() == 0) {
          return 1;
          exit;
        }else{
          return 3;
          exit;
        }
     
    }
    /**
     * [get_design_approver_list description]
     * @return [type] [description]  here approver user list is send for mr creation  only selected approver
     */
    public function get_design_approver_list(){
      $data_array_approver = array('Status' => 1,'role_id'=>8 );
      $query_approver=$this->db->get_where('master_admin',$data_array_approver);
      if($query_approver->num_rows() == 0){
        $data_send = array('no_user' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_approver->result();
        $data_send = array('no_user' =>1, 'user_approver'=>$results);
        return $data_send;
        exit;
      }     
    }
    /**
     * [get_design_approver_single description] here detail information of approver is send while storing information 
     * @param  [type] $data_id [description]
     * @return [type]          [description]
     */
    public function get_design_approver_single($data_id){
      $data_array_approver = array('Status' => 1,'role_id'=>8,'slno'=>$data_id );
      $query_approver=$this->db->get_where('master_admin',$data_array_approver);
      if($query_approver->num_rows() == 0){
        $data_send = array('no_user' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_approver->result();
        $data_send = array('no_user' =>1, 'user_approver'=>$results);
        return $data_send;
        exit;
      }     
    }
    public function get_design_user_single($data_id){
      $data_array_approver = array('Status' => 1,'email_id'=>$data_id);
      $query_approver=$this->db->get_where('master_admin',$data_array_approver);
      if($query_approver->num_rows() == 0){
        $data_send = array('no_user' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_approver->result();
        $data_send = array('no_user' =>1, 'user_approver'=>$results);
        return $data_send;
        exit;
      }     
    }
    /**
     * [get_design_material_category_list description]  HERE LIS TO F MATERIAL CATEGORY IS BEEB which apporoced or status actioe will send to list 
     * @return [type] [description]
     */
    public function get_design_material_category_list(){ 

      $data_array_materials_category = array('status' => 1);
      $query_material_category=$this->db->get_where('master_category',$data_array_materials_category);
      if($query_material_category->num_rows() == 0){
        $data_send = array('no_materials' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_category->result();
        $data_send = array('no_materials' =>1, 'materials_list'=>$results);
        return $data_send;
        exit;
      }     
    }
    /**
     * [get_design_material_category_single description]
     * @param  [type] $data_id [description]
     * @return [type]          [description]
     */
     public function get_design_material_category_single($data_id){

      $data_array_materials_category = array('status' => 1,'Slno_cat'=>$data_id);
      $query_material_category=$this->db->get_where('master_category',$data_array_materials_category);
      if($query_material_category->num_rows() == 0){
        $data_send = array('no_materials' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_category->result();
        $data_send = array('no_materials' =>1, 'materials_list'=>$results);
        return $data_send;
        exit;
      }     
    }
    /**
     * [get_design_job_single description]
     * @param  [type] $data_id  [description]
     * @param  [type] $email_id [description]
     * @return [type]           [description]
     */
    public function get_design_job_single($data_id,$email_id){
      $this->db->select('*');
      $this->db->from('master_project');
      $this->db->join('assign_project_user', ' (assign_project_user.project_slno = master_project.Project_Slno  AND master_project.status=1 ) ', 'right outer' );
                // $this->db->join('city', 'city.user_id = users.id','left');
      $this->db->where('assign_project_user.email_id', $email_id); 
      $this->db->where('master_project.Project_Slno', $data_id); 
      $query_job_code = $this->db->get();     
      if($query_job_code->num_rows() == 0){
        $data_send = array('no_job_code' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_job_code->result();
        $data_send = array('no_job_code' =>1, 'job_code_list'=>$results);
        return $data_send;
        exit;
      }     
    }
    public function get_design_master_items_material($value){
      // master_items_material
      $data_array_materials_item = array('status' => 1,'Category_slno'=>$value);
      $query_material_item=$this->db->get_where('master_items_material',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_materials_item' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_materials_item' =>1, 'materials_list'=>$results);
        return $data_send;
        exit;
      }  
    }


    public function get_design_master_items_material_single($value){
      // master_items_material
      $data_array_materials_item = array('status' => 1,'Slno_item'=>$value);
      $query_material_item=$this->db->get_where('master_items_material',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_materials_item' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_materials_item' =>1, 'materials_list'=>$results);
        return $data_send;
        exit;
      }  
    }

     public function get_design_master_items_material_single_m($value){
      // master_items_material
      $data_array_materials_item = array('status' => 1,'slno_master_item'=>$value);
      $query_material_item=$this->db->get_where('master_category_item',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_materials_item' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_materials_item' =>1, 'materials_list'=>$results);
        return $data_send;
        exit;
      }  
    }
     public function get_design_master_items_material_single_technical($value){
      // master_items_material
      $data_array_materials_item = array('status' => 1,'material_slno'=>$value);
      $query_material_item=$this->db->get_where('master_technical_detail',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_technical' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_technical' =>1, 'technical_list'=>$results);
        return $data_send;
        exit;
      }  
    }

     public function get_design_mr_file_list($value,$value1){
      // master_items_material
      $data_array_mr_files = array('mr_no_id' =>$value1,'slno_mr_id'=>$value);
      $query_mr_files =$this->db->get_where('master_mr_file_upload',$data_array_mr_files);
      if($query_mr_files->num_rows() == 0){
        $data_send = array('no_files' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_mr_files->result();
        $data_send = array('no_files' =>1, 'files_list'=>$results);
        return $data_send;
        exit;
      }  
    }
     public function get_design_mr_file_list_m($value,$value1,$value2){
      // `pr_no`, `pr_no_slno`, `file_title`, `edit_id`, `attach_name`, `file_name_actucal`
      // master_items_material
      $data_array_mr_files = array('pr_no' =>$value,'pr_no_slno'=>$value1,'job_code_slno'=>$value2);
      $query_mr_files =$this->db->get_where('master_mr_file_upload_m',$data_array_mr_files);
      if($query_mr_files->num_rows() == 0){
        $data_send = array('no_files' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_mr_files->result();
        $data_send = array('no_files' =>1, 'files_list'=>$results);
        return $data_send;
        exit;
      }  
    }
    public function get_design_mr_file_list_check($value,$value1){
      // master_items_material
      $data_array_mr_files = array('mr_no_id' =>$value1,'slno_mr_id'=>$value);
      $query_mr_files =$this->db->get_where('master_mr_file_upload',$data_array_mr_files);
      if($query_mr_files->num_rows() == 0){
        $data_send = array('no_files' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_mr_files->result();
        $data_send = array('no_files' =>1);
        return $data_send;
        exit;
      }  
    }
    public function get_design_mr_file_list_check_m($value,$value1,$value2){
      // master_items_material
      $data_array_mr_files = array('pr_no' =>$value,'pr_no_slno'=>$value1,'job_code_slno'=>$value2);
      $query_mr_files =$this->db->get_where('master_mr_file_upload_m',$data_array_mr_files);
      if($query_mr_files->num_rows() == 0){
        $data_send = array('no_files' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_mr_files->result();
        $data_send = array('no_files' =>1);
        return $data_send;
        exit;
      }  
    }
    /**
     * [design_common_insert_id description] here last imsert id is generated where it is tag with other parameter
     * @param  [type] $table [description]
     * @param  [type] $data  [description]
     * @return [type]        [description]
     */
    public function design_common_insert_id($data){        
      $query=$this->db->insert('master_mr_material_item', $data);
      $this->db->last_query();
      if($query){
        return $this->db->insert_id();
      }else{
        return 0;
      }

    }
    public function design_common_insert_id_m($data){        
      $query=$this->db->insert('master_mr_material_item_m', $data);
      $this->db->last_query();
      if($query){
        return $this->db->insert_id();
      }else{
        return 0;
      }

    }
     public function get_design_master_single_technical($value){
      // master_items_material
      $data_array_materials_item = array('status' => 1,'Slno_technical'=>$value);
      $query_material_item=$this->db->get_where('master_technical_detail',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_technical' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_technical' =>1, 'technical_list'=>$results);
        return $data_send;
        exit;
      }  
    }
     public function design_Mr_technical_insert_id($data){        
      $query=$this->db->insert('master_mr_technical_parameter_info', $data);
      $this->db->last_query();
      if($query){
        return $this->db->insert_id();
      }else{
        return 0;
      }

    }
    public function master_mr_job_details_value($value,$id){
      // print_r($id);
      
        $query=$this->db->update('master_mr_job_details', $value,$id);

        // echo $this->db->last_query();
        // exit();
        if($query){
          return $this->db->insert_id();
        }else{
          return 0;
        }
    }
     public function master_mr_job_details_value_m($value,$id){
      // print_r($id);
      
        $query=$this->db->update('master_mr_job_details_m', $value,$id);

        echo $this->db->last_query();
       
        if($query){
          return 1;
        }else{
          return 0;
        }
    }
   
    public function design_mr_submited_list($value=''){
      // `job_code_id_slno`, `job_code_id`
     
      if(!empty($value)){
       $this->db->where('job_code_id ',$value);
       $this->db->where('status ', 1);
      }else{
        $this->db->select('job_code_id');
        $this->db->group_by('job_code_id');
      }     
      $query = $this->db->get('master_mr_job_details');
      if($query->num_rows() == 0){
        $data_send = array('no_submited' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query->result();
        $data_send = array('no_submited' =>1, 'submited_list'=>$results);
        return $data_send;
        exit;
      }  
    }
     /**
     * [design_mr_drafted_list description] here is the drafted version of mr list
     * @return [type] [description]
     */
    public function design_mr_drafted_list($value='',$value1=''){
      if(!empty($value)){
        $this->db->where('job_code_id ',$value);
      }
      //  this been changed please find error not me back 16 jan 2019
      if(!empty($value1)){
        $this->db->where('creators_id ',$value1);
      }
      $this->db->where('status ', 4);
      $this->db->or_where('status ', 5);
      $query = $this->db->get('master_mr_job_details');
        if($query->num_rows() == 0){
        $data_send = array('no_drafted' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query->result();
        $data_send = array('no_drafted' =>1, 'drafted_list'=>$results);
        return $data_send;
        exit;
      }  
    }
    public function design_mr_resubmission_list($value=''){
       if(!empty($value)){
        $this->db->where('job_code_id ',$value);
      }
      $this->db->where('status ', 6);      
      $query = $this->db->get('master_mr_job_details');
        if($query->num_rows() == 0){
        $data_send = array('no_drafted' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query->result();
        $data_send = array('no_drafted' =>1, 'drafted_list'=>$results);
        return $data_send;
        exit;
      }  

      # code...
    }
    public function get_design_master_mr_items_material_single($edit_id,$Mr_no,$slno_mr_id){
      $data_array_materials_item = array('mr_no_item' => $Mr_no,'slno_mr_id'=>$slno_mr_id,'edit_id'=>$edit_id);
      $query_material_item=$this->db->get_where('master_mr_material_item',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_item' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_item' =>1, 'item_list'=>$results);
        return $data_send;
        exit;
      }
    }
    public function get_design_master_mr_technical_items_material_single($edit_id,$Mr_no,$slno_mr_id){
    
      $data_array_materials_item = array('mr_no_tech' => $Mr_no,'slno_mr_id_tech'=>$slno_mr_id,'edit_id'=>$edit_id);
      $query_material_item=$this->db->get_where('master_mr_technical_parameter_info',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_item_tech' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_item_tech' =>1, 'item_list_tech'=>$results);
        return $data_send;
        exit;
      }
    }
    /**
     * [get_design_master_loaction_list description] here location information is been user by mr creater
     * 
     * @return [type] [description]
     */
    public function get_design_master_loaction_list($value=''){
      if(empty($value)){
        $data_array_materials_item = array('status' => 1);
        $query_material_item=$this->db->get_where('master_loaction_details',$data_array_materials_item);
        if($query_material_item->num_rows() == 0){
          $data_send = array('no_location' =>2 );
          return $data_send;
          exit;
        }else{
          $results=$query_material_item->result();
          $data_send = array('no_location' =>1, 'item_location'=>$results);
          return $data_send;
          exit;
        }
      }else{
        $data_array_materials_item = array('status' => 1,'slno_loc'=>$value);
        $query_material_item=$this->db->get_where('master_loaction_details',$data_array_materials_item);
        if($query_material_item->num_rows() == 0){
          $data_send = array('no_location' =>2 );
          return $data_send;
          exit;
        }else{
          $results=$query_material_item->result();
          $data_send = array('no_location' =>1, 'item_location'=>$results);
          return $data_send;
          exit;
        } 
      }
    }
  public function get_design_master_vehcile_list($value=''){
    if(empty($value)){
      $data_array_materials_item = array('status' => 1);
      $query_material_item=$this->db->get_where('master_vehicle',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_vehcile' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_vehcile' =>1, 'item_vehcile'=>$results);
        return $data_send;
        exit;
      }
    }else{
      $data_array_materials_item = array('status' => 1,'Slno_vehicle'=>$value);
      $query_material_item=$this->db->get_where('master_vehicle',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_vehcile' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_vehcile' =>1, 'item_vehcile'=>$results);
        return $data_send;
        exit;
      }  
    }
  }
  public function get_design_master_mr_vechile_single($edit_id,$Mr_no,$slno_mr_id){
    // `mr_no_vehicle`, `slno_mr_id_vehicle`, `edit_it`
      $data_array_materials_item = array('mr_no_vehicle' => $Mr_no,'slno_mr_id_vehicle'=>$slno_mr_id,'edit_it'=>$edit_id);
      $query_material_item=$this->db->get_where('master_mr_vehicle_mr_detail',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_vechile' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_vechile' =>1, 'item_vechile_list'=>$results);
        return $data_send;
        exit;
      }
    }
    public function get_design_master_mr_location_details($edit_id,$Mr_no,$slno_mr_id){
    // `mr_id_location`, `mr_slno_id`, `edit_id`
      $data_array_materials_item = array('mr_id_location' => $Mr_no,'mr_slno_id'=>$slno_mr_id,'edit_id'=>$edit_id);
      $query_material_item=$this->db->get_where('master_mr_location',$data_array_materials_item);
      if($query_material_item->num_rows() == 0){
        $data_send = array('no_mr_location' =>2 );
        return $data_send;
        exit;
      }else{
        $results=$query_material_item->result();
        $data_send = array('no_mr_location' =>1, 'item_location_list'=>$results);
        return $data_send;
        exit;
      }
    }
    public function get_design_master_mr_get_no_entry($type,$job_code){
    // `mr_id_location`, `mr_slno_id`, `edit_id``job_code_id`, `status`
      if($type==1){
        $data_array_materials_item = array('job_code_id' => $job_code,'status'=>1);
        $query_material_item=$this->db->get_where('master_mr_job_details',$data_array_materials_item);
        return $query_material_item->num_rows();
      }else{
          // $data_array_materials_item = array('job_code_id' => $job_code);
          $this->db->where('job_code_id ',$job_code);
          $this->db->where('status ', 4);
          $this->db->or_where('status ', 5);        
          $query_material_item=$this->db->get_where('master_mr_job_details');
           // echo $this->db->last_query();
          return $query_material_item->num_rows();

      }
    
      // $data_array_materials_item = array('mr_id_location' => $Mr_no,'mr_slno_id'=>$slno_mr_id,'edit_id'=>$edit_id);
      // $query_material_item=$this->db->get_where('master_mr_location',$data_array_materials_item);
      // if($query_material_item->num_rows() == 0){
      //   $data_send = array('no_mr_location' =>2 );
      //   return $data_send;
      //   exit;
      // }else{
      //   $results=$query_material_item->result();
      //   $data_send = array('no_mr_location' =>1, 'item_location_list'=>$results);
      //   return $data_send;
      //   exit;
      // }
    }


}